language: python
python:
  - "3.5"
  - "3.8"

env:
  - TOXENV=django22
  - TOXENV=quality
  - TOXENV=without-django

matrix:
  allow_failures:
    - python: 3.8

install:
  - make requirements
  - pip install coveralls
script:
  - tox -- --hypothesis-profile=ci
after_success:
  - coveralls
deploy:
  provider: pypi
  user: edx
  password:
    secure: cnCf0zDyTEJycCDcxhH1GsvOWNGImjwc8WIrD/D5Hsk7p0IeMaEjc/t6gc1LO2iQKGlZq/BLDxUBmsEbrQUD1wvSBg/J+9Ji6yn9jJ87X6QSNq+Xy0brLe9RAeMElG3OLqbj6FHRMzk2EmOEJXI9ATqlXfdqFwgKCYrvf2GT2Ug=
  on:
    tags: true
    python: "3.5"
    condition: "$TOXENV = django22"
    distributions: sdist bdist_wheel
    repo: edx/opaque-keys
